### ISSUE TITLE
modeleditor.save should write file using latin-1 encoding and DOS line separators for compatibility with IDFEditor

### ISSUE THREAD

**Issue by pachi** [santoshphilip/eppy#68] opened 2015-11-25 13:05 UTC
When using modeleditor.save() on linux it uses UNIX style line separators, which fail with EnergyPlus IDFEditorl.
Also, if the model has been created using utf-8 data, the file is saved with that format and strings are wrongly encoded in IDFEditor (using latin-1 fixes the problem for me).

**Comment by pachi** [comment] 2015-11-25 13:18
using this code, instead of the .save() method, works for me:

with io.open(idf.idfname, 'w', newline='\r\n', encoding='latin-1') as ff:
    ff.write(idf.idfstr())

**Comment by santoshphilip** [comment] 2015-11-26 22:23
the save function has a keyword argument that you can use
This is not yet in the documentation :-(

    idf.save(lineendings='windows')
    
The function declaration looks like this:`    

    def save(self, filename=None, lineendings='default'):
        """lineendings = ['default', 'windows', 'unix' ]"""
        # rest of code
        
Also saveas and savecopy have the same argument:

    def saveas(self, filename, lineendings='default'):
        self.idfname = filename
        self.save(lineendings=lineendings)
    def savecopy(self, filename, lineendings='default'):
        """save a copy as filename"""
        self.save(filename, lineendings=lineendings)
        
        
        
Regarding the encoding functionality, it should probably look like this:

    def save(self, filename=None, lineendings='default', encoding='latin-1'):
        """lineendings = ['default', 'windows', 'unix' ]"""
        # encoding functionality needs to be coded
        
Could you take a look at what it would take to put in the encoding functionality ?        
If can include it in the release version

**Comment by jamiebull1** [comment] 2016-01-30 15:45
@santoshphilip I had a bit of downtime so I've written a fix for this and tested on linux. I've also added unit tests for encoding, line endings, and the regular IDF.save function. I branched off `master` though, which might not be the best so I haven't opened a pull request. If you can let me know what branch is best to be working on (or create a new one) then I can make the changes on that and open a PR.

The diff is [here](https://github.com/santoshphilip/eppy/compare/master...jamiebull1:latin1-encoding) if you want to take a look.

**Comment by santoshphilip** [comment] 2016-01-30 16:39
@jamiebull1 branch off `develop`. It is stable.

**Comment by santoshphilip** [comment] 2016-02-02 01:15
Jamie,
I made a major merge into branch `develop`. 
Just flagging you in case you wish to merge it into the branch you are working on.
(You don't have to)

**Comment by pachi** [comment] 2016-02-02 08:35
Very nice, and thanks you both for your work. I'd like to point out that it would be very convenient to change lineendings so it defaults to 'windows', otherwise the generated file fails to work with IDFEditor. *nix systems don't have any problems with dos line endings so there's no harm in it, IMHO.

**Comment by jamiebull1** [comment] 2016-02-02 08:42
Does IDFEditor expect DOS line endings on Linux?

**Comment by jamiebull1** [comment] 2016-02-02 09:25
@santoshphilip No changes required on this one. It's still mergeable with the latest `develop` branch.

**Comment by pachi** [comment] 2016-02-02 09:38
My problem is that, while I work on a Linux machine (and I don't use IDFEditor), the models are also run on windows machines and other people use IDFEditor on windows, and this fails.

**Comment by jamiebull1** [comment] 2016-02-02 11:54
Got it. Yes, that sounds like a pretty common use case - I only ever use
IDFEditor on Windows so just luck that I've never come across this problem.
Sounds like worth reporting as a bug with IDFEditor, but I see no reason
not to work around it as you suggest.

**Comment by santoshphilip** [comment] 2016-02-02 16:48
Yes, this is a common use case. I edit my files on a mac and then move onto the windows machine. At thispoint IDFEditor is unable to open my file :-(

We have three options for the save(). They are:

### Option A.

    idf.save() # -> Save in the native format of the host machine
        # if you are on a unix machine, the line endings would be unix
        # if you are on a windows machine, the line endings would be DOS
    idf.save(lineendings='windows') # -> forces the lineendings to be windows


### Option B.

    idf.save() # -> save in the existing file format
        # if the file format is unix, the line endings continue to be unix
        # if the file format is windows, the line endings continue to be windows
    idf.save(lineendings='windows') # -> forces the lineendings to be windows


### Option C.

    idf.save() # -> always save in windows format
    idf.save(lineendings='windows') # -> redundant but still works


## Pros and Cons of each option

### Option A.

    idf.save() # -> Save in the native format of the host machine
        # if you are on a unix machine, the line endings would be unix
        # if you are on a windows machine, the line endings would be DOS
    idf.save(lineendings='windows') # -> forces the lineendings to be windows

**Pros:**
- follows pythonic behavior. This is how python code would normally behave
- follows zen of python -> Explicit is better than implicit

**Cons:**
- you have to force line endings to be `windows` when you are on a unix machine


### Option B.

    idf.save() # -> save in the existing file format
        # if the file format is unix, the line endings continue to be unix
        # if the file format is windows, the line endings continue to be windows
    idf.save(lineendings='windows') # -> forces the lineendings to be windows

This is how the software BBedit and TextWrangler work.

**Pros:**
- This is how a lot of text editing software work
- This is expected behavior in the GUI environment

**Cons:**
- not obviously pythonic
- plain vanilla python code does not behave this way



### Option C.

    idf.save() # -> always save in windows format
    idf.save(lineendings='windows') # -> redundant but still works

**Pros:**
- will always work with present version of IDFEditor

**Cons:**
- This is a special case for IDFEditor
- IDFEditor may change and this may no longer be a special case
- breaks Zen of python -> Special cases aren't special enough to break the rules


**Option A** is already implemented in the `master` branch, but not documented

Let me know your thoughts

**Comment by jamiebull1** [comment] 2016-02-02 22:53
Looks like you've thought a bit about this, Santosh. My vote would be for option B - leave the endings unchanged unless specified. Option A is also not bad, and has the advantage of already being implemented.

My slight change of heart is down to the fact that the IDFEditor can't handle unix line endings seems like something to be handled on that end. On consideration i tend to agree with Santosh - we shouldn't do something unexpected to handle just that flaw. I'll raise an issue in the EnergyPlus repo.

**Comment by santoshphilip** [comment] 2016-02-03 06:34
I have some discomfort in going with **Option B.**
I'll try to articulate this in my next post (need some time to gather my thoughts :-)

**Comment by pachi** [comment] 2016-02-03 08:37
I propose a third option D:
```
idf.save() # -> always save in windows format
idf.save(lineendings='unix') # -> override default behaviour.
```

In my opinion, we are not just handling generic text files here. The fact that idf files are text files is just a detail and we have an application specific format which eppy should handle with specific knowledge about the format. This is more or less what happens with the encoding attribute.

I'd only keep things as is in the case that energyplus on linux can't handle DOS lineendings (I can't check now) and, of course, I think that explicitly overriding the default behaviour should be allowed.

**Comment by santoshphilip** [comment] 2016-02-04 07:02
I'll check the following tomorrow 
- test E+ on Unix with DOS line endings
- test E+ on windows with unix line endings

If they both run, then only IDFEditor is problematic.

**Comment by santoshphilip** [comment] 2016-02-05 00:52
On Linux
- E+ runs files with DOS line endings
- E+ runs files with Unix line endings

On Windows
- E+ runs files with DOS line endings
- E+ runs files with Unix line endings

As far I can make out only IDF Editor is sensitive to line endings.
I recommend that we stay with **Option A**

    idf.save() # -> Save in the native format of the host machine
        # if you are on a unix machine, the line endings would be unix
        # if you are on a windows machine, the line endings would be DOS
    idf.save(lineendings='default') # -> same as idf.save()
    idf.save(lineendings='windows') # -> forces the lineendings to be windows
    idf.save(lineendings='unix') # -> forces the lineendings to be unix

**Comment by pachi** [comment] 2016-02-05 16:01
Then, maybe we should just file a but on IDFEditor so it can handle non DOS files properly.
Thanks you both for the fine work!

**Comment by JasonGlazer** [comment] 2016-02-05 16:15
I just added a suggestion on this topic to the EnergyPlus repo.

**Comment by santoshphilip** [comment] 2016-02-07 04:31
this has been fixed and merged into branch `develop`

**Closed by santoshphilip** 2016-02-07 04:31 UTC
