### ISSUE TITLE
Running EnergyPlus from Eppy

### ISSUE THREAD

**Issue by yahyasheikhnejad** [santoshphilip/eppy#237] opened 2019-05-21 15:12 UTC
after importing all required modules:

import os
import sys
import numpy as np
from eppy import *				
from eppy import modeleditor
from eppy.modeleditor import IDF

EPPY Code [from https://pythonhosted.org//eppy/runningeplus.html]:

    iddfile = "C:/EnergyPlusV8-9-0/PreProcess/IDFVersionUpdater/V8-3-0-Energy+.idd"
    IDF.setiddname(iddfile)
    idfname = "C:/EnergyPlusV8-9-0/ExampleFiles/BasicsFiles/Exercise1A.idf"
    epwfile = "C:/EnergyPlusV8-9-0/WeatherData/USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw"
    idf = IDF(idfname, epwfile)
    idf.run()

Result:

Traceback (most recent call last):
File "yeppy5.py", line 28, in 
idf.run()
File "C:\Users\yahya\AppData\Local\Continuum\anaconda3\lib\site-packages\eppy\modeleditor.py", line 1009, in run
self.saveas('in.idf')
File "C:\Users\yahya\AppData\Local\Continuum\anaconda3\lib\site-packages\eppy\modeleditor.py", line 974, in saveas
self.save(filename, lineendings, encoding)
File "C:\Users\yahya\AppData\Local\Continuum\anaconda3\lib\site-packages\eppy\modeleditor.py", line 947, in save
with open(filename, 'wb') as idf_out:
PermissionError: [Errno 13] Permission denied: 'in.idf'

EP version 8.9.0, eppy 0.5.48, Python  3.6.5.
window 10 does not allow me to change .py files of eppy program [access is denied].
hence I have not any chance to correct embedded code inside eppy program.
please help me to solve these error while running eppy program.

**Comment by santoshphilip** [comment] 2019-05-21 15:19
see @jasonglazer comment at

https://github.com/santoshphilip/eppy/commit/55410ff7c11722f35bc4331ff5e00a0b86f787e1#commitcomment-33621430

**Comment by yahyasheikhnejad** [comment] 2019-05-21 16:46
@santoshphilip thanks, but running .idf file still is the main problem remaining unsolved!  
Please help! Thank you so much for your support.

**Comment by jamiebull1** [comment] 2019-05-21 16:54
You can pass an output directory to the `run` method.

    idf.run(output_directory="somewhere/you/can/write/to")

**Comment by yahyasheikhnejad** [comment] 2019-05-21 17:03
> You can pass an output directory to the `run` method.
> 
> ```
> idf.run(output_directory="somewhere/you/can/write/to")
> ```

TypeError: run() takes 1 positional argument but 2 were given

which means this method takes only "self" as its sole argument and will not accept path!
I am right?

**Comment by yahyasheikhnejad** [comment] 2019-05-21 18:45
@santoshphilip @jamiebull1 
I appreciate your time spending on my question, 
I tried suggested format but still running .idf file still is the main problem remaining unsolved!
idf.run(output_directory='c:/') will again results in PermissionError: [Errno 13] Permission denied: 'in.idf'
Please help!

**Comment by jamiebull1** [comment] 2019-05-21 19:19
Try setting your current working directory with `os.chdir("somewhere/you/can/write/to")`. It looks like the offending line is in `IDF.run()`:

    def run(self, **kwargs):
        ....
        # write the IDF to the current directory
        self.saveas('in.idf')

If your cwd isn't writeable then this line will fail.

**Comment by yahyasheikhnejad** [comment] 2019-05-28 17:05
Dear @santoshphilip and @jamiebull1
I do appreciate if you could help me with this new type of error saying there is an indentation problem inside modeleditor.py!!!

>>> import eppy
>>> from eppy import modeleditor

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\yahya\AppData\Local\Continuum\anaconda3\lib\eppy\modeleditor.py", line 28, in <module>
    from eppy.runner.run_functions import run
  File "C:\Users\yahya\AppData\Local\Continuum\anaconda3\lib\eppy\runner\run_functions.py", line 93
    for y,z in processed_runs:
                             ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by yahyasheikhnejad** [comment] 2019-05-28 17:41
Dear @santoshphilip and @jamiebull1
first, I want you to know that I am grateful for your help and support till now.
I have copied all the required files to where I can write and save. now another problem is arisen from command run():

Code:
 
import os
from eppy import *				
from eppy import modeleditor
from eppy.modeleditor import IDF

os.chdir("C:/Yahya/EP")
iddfile = "Energy+V7_2_0.idd"        # this file is in specified directory
IDF.setiddname(iddfile)
epwfile = "USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw"     # this file is in specified directory
fname4 = "yahya.idf"                      # this file is in specified directory
idf4 = IDF(fname4, epwfile)
print("it's done!")                           # to check out if code will be executed well till here

Running the code results in:

it's done!
Traceback (most recent call last):
  File "yeppy6.py", line 23, in <module>
    idf4.run()
  File "C:\Users\yahya\AppData\Local\Programs\Python\Python36\lib\site-packages\eppy\modeleditor.py", line 1004, in run
    run(self, self.epw, **kwargs)
  File "C:\Users\yahya\AppData\Local\Programs\Python\Python36\lib\site-packages\eppy\runner\run_functions.py", line 238, in run
    check_call(cmd)
  File "C:\Users\yahya\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Users\yahya\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\yahya\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\yahya\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

running the code inside eppy directory gives permission denied error and in out of its directory (writeable folder) gives another error (cannot find!). please help!

**Comment by jamiebull1** [comment] 2019-05-28 17:46
Can you try adding a breakpoint or a print statement and see what the value of `cmd` is here:

    File "C:\Users\yahya\AppData\Local\Programs\Python\Python36\lib\site-packages\eppy\runner\run_functions.py", line 238, in run
    check_call(cmd)

**Comment by yahyasheikhnejad** [comment] 2019-05-28 19:52
> Can you try adding a breakpoint or a print statement and see what the value of `cmd` is here:
> 
> ```
> File "C:\Users\yahya\AppData\Local\Programs\Python\Python36\lib\site-packages\eppy\runner\run_functions.py", line 238, in run
> check_call(cmd)
> ```

cmd =  ['C:/EnergyPlusV7-2-0\\energyplus.exe', '--output-directory', 'C:\\Yahya\\EP', '--weather', 'C:\\Yahya\\EP\\USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw', 'C:\\Yahya\\EP\\in.idf']

**Comment by jamiebull1** [comment] 2019-05-28 19:53
And do all of those paths actually exist?

**Comment by JasonGlazer** [comment] 2019-05-28 20:17
Don't use \ it will think that is and the next character is an escape character. Use / instead or else \\

**Comment by yahyasheikhnejad** [comment] 2019-05-29 17:13
> And do all of those paths actually exist?

of course they do!
this complicated problem is going to kill me! everything looks fine, I have checked everything.
the error seems unreasonable!

**Comment by yahyasheikhnejad** [comment] 2019-05-29 17:17
> Don't use '\' it will think that is and the next character is an escape character. Use '/' instead or else '\\'

I didn't...!
I presented my code above, as you may see, all directories are written with "/".
"\" appeared as a result of printing variable "cmd" in the file of "run_functions.py" as recommended by @jamiebull1 .

**Comment by jamiebull1** [comment] 2019-05-29 17:46
>of course they do!

Sorry, I should have said "which one of those paths doesn't actually exist?" The error tells us that one of them doesn't for one reason or another, at least at the point when the subprocess is looking for it.

Some ideas: 

- Check @JasonGlazer 's point about \ vs / by setting a breakpoint just before the subprocess is called, and checking you can access the files from the Python shell with `os.path.isfile(<path>)`
- Is EnergyPlus in the default directory? Are you actually using EnergyPlus v7.2 and the executable is "C:/EnergyPlusV7-2-0\energyplus.exe"?
- Try running with the `verbose="v"` option which may give some more clues

**Comment by yahyasheikhnejad** [comment] 2019-05-30 08:59
> > of course they do!
> Sorry, I should have said "which one of those paths doesn't actually exist?" The error tells us that one of them doesn't for one reason or another, at least at the point when the subprocess is looking for it.
> Some ideas:
> * Check @JasonGlazer 's point about \ vs / by setting a breakpoint just before the subprocess is called, and checking you can access the files from the Python shell with `os.path.isfile(<path>)`
> * Is EnergyPlus in the default directory? Are you actually using EnergyPlus v7.2 and the executable is "C:/EnergyPlusV7-2-0\energyplus.exe"?
> * Try running with the `verbose="v"` option which may give some more clues. For one thing, it will print the generated command to std out so you can try running it directly from the command line, and make changes there to work out what the issue is.

Dear @jamiebull1 
first of all, thank you so much for being so nice to me and step by step helping me to solve my problem. I do appreciate. 
second, I checked all the files inside "cmd" value, except "C:/EnergyPlusV7-2-0/energyplus.exe" all of the files exist.
the problem with this file is the version of EP!!
correct file address is: "C:\EnergyPlusV8-9-0/energyplus.exe"
while EP V8-9-0 is installed in my laptop, how eppy module recognized another version? 
or perhaps EnergyPlusV7-2-0 is the default of the eppy module!

**Comment by jamiebull1** [comment] 2019-05-30 14:39
Now we're getting somewhere. Here is the offending line in your code:

`iddfile = "Energy+V7_2_0.idd" # this file is in specified directory`

You need to set the IDD for the version of EnergyPlus you're using, and also be sure that it matches the version in the IDF you're using.

**Comment by santoshphilip** [comment] 2019-05-30 14:53
OK .. I think I know where the problem is coming from. I am not at a computer yet. So I can't test anything. Here are my thoughts:

don't use this:
iddfile = "Energy+V7_2_0.idd" # this file is in specified directory
Use:

iddfile = C:/EnergyPlusV8-9-0/Energy+.idd 
IDF.setiddname(iddfile)

make sure your IDF file has the lines::

    version,
    8.9;

See if it works now

**Comment by santoshphilip** [comment] 2019-05-30 14:58
didn't see @jamiebull1 reply when I posted. Looks like we are saying the same things :-)

**Comment by yahyasheikhnejad** [comment] 2019-05-30 15:03
Dear @santoshphilip and @jamiebull1 
thank both of you for all your help and support. I appreciate the time you were spending to solve my problem. I will try and write the result here.

**Comment by yahyasheikhnejad** [comment] 2019-05-30 16:03
Dear @santoshphilip  and @jamiebull1 
the problem is solved!
Thanks a million! 
I truly appreciate your help and support.

**Comment by santoshphilip** [comment] 2019-05-30 17:56
@yahyasheikhnejad ,

I have been writing some code that will make what you are doing easier. 

this code is in the project [witheppy](https://github.com/pyenergyplus/witheppy)

- You need to install witheppy 
    - pip install witheppy
- You also need the latest eppy >= 0.5.49
    - pip uninstall eppy
    - pip install eppy

The documentation for the function is is [here](https://witheppy.readthedocs.io/en/latest/userdocs.html#ep-launch-functionality-with-eppy)

The code you use will look like this::

    # works with eppy > 0.5.49
    fname = "pathtoidffile/myidf.idf"
    weatherfile = "pathtoweatherfile/USA_CA_San.Francisco.Intl.AP.724940_TMY3.epw"
    
    import eppy
    idf = eppy.openidf(fname, epw=weatherfile)
    
    import witheppy
    import witheppy.runner
    witheppy.runner.eplaunch_run(idf)
    
This should work fine for what you are doing

@jamiebull1 , @JasonGlazer , I would apreciate if you could look at the EP-Launch functionality in witheppy and see if I am missing anything. Am I missing any args I should be using ? For easy reference, [this is the function docs](https://witheppy.readthedocs.io/en/latest/witheppy.html)  and  [this is the code](https://witheppy.readthedocs.io/en/latest/_modules/witheppy/runner.html#eplaunch_run)

**Comment by yahyasheikhnejad** [comment] 2019-05-31 09:55
Dear @santoshphilip 
Thank you so much for being so kind and for your high responsibility.
you, @jamiebull1 and @JasonGlazer are nice scientific guys who help me in my problem and I extremely appreciate it.

**Comment by yahyasheikhnejad** [comment] 2019-05-31 09:58
> @yahyasheikhnejad ,
> 
> I have been writing some code that will make what you are doing easier.
> 
> this code is in the project [witheppy](https://github.com/pyenergyplus/witheppy)
> 
> * You need to install witheppy
>   
>   * pip install witheppy
> * You also need the latest eppy >= 0.5.49
>   
>   * pip uninstall eppy
>   * pip install eppy
> 
> The documentation for the function is is [here](https://witheppy.readthedocs.io/en/latest/userdocs.html#ep-launch-functionality-with-eppy)
> 
> The code you use will look like this::
> 
> ```
> # works with eppy > 0.5.49
> fname = "pathtoidffile/myidf.idf"
> weatherfile = "pathtoweatherfile/USA_CA_San.Francisco.Intl.AP.724940_TMY3.epw"
> 
> import eppy
> idf = eppy.openidf(fname, epw=weatherfile)
> 
> import witheppy
> import witheppy.runner
> witheppy.runner.eplaunch_run(idf)
> ```
> 
> This should work fine for what you are doing
> 
> @jamiebull1 , @JasonGlazer , I would apreciate if you could look at the EP-Launch functionality in witheppy and see if I am missing anything. Am I missing any args I should be using ? For easy reference, [this is the function docs](https://witheppy.readthedocs.io/en/latest/witheppy.html) and [this is the code](https://witheppy.readthedocs.io/en/latest/_modules/witheppy/runner.html#eplaunch_run)

Dear @santoshphilip 
would you please do me a favor and explain this command line: witheppy.runner.eplaunch_run(idf)
what does this line do?
or
what is the role of this line?

**Comment by santoshphilip** [comment] 2019-05-31 14:23
It will run the simulation.

Same as idf.run()
except that it has some default arguments. See the links:
- https://witheppy.readthedocs.io/en/latest/userdocs.html#ep-launch-functionality-with-eppy
- https://witheppy.readthedocs.io/en/latest/_modules/witheppy/runner.html#eplaunch_run

Santosh

**Comment by santoshphilip** [comment] 2019-05-31 18:04
@yahyasheikhnejad , dont worry about the witheppy stuff if you got everything working.
I am going to consider this issue resolved and I'll close it

**Closed by santoshphilip** 2019-05-31 18:04 UTC
