### ISSUE TITLE
eplusout.expidf not found

### ISSUE THREAD

**Issue by intelligent-222** [santoshphilip/eppy#309] opened 2020-10-23 22:19 UTC
I am running EP8-9 on linux and when I run my code I received the following error. I have searched online and it seems that no one else has same issue. can you please help me. I am restricted to use EP 8-9 since the High Performance Computer that I've been working on supports this version only. The code is running well on my windows OS. I appreciate if anyone can help me with this issue.

here is the error file:
Contents of EnergyPlus error file at /nfs/speed-scratch/USER/eplusout.err
Program Version,EnergyPlus, Version 8.9.0-40101eaafd, YMD=2020.10.23 16:05,
   **  Fatal  ** Input file path /nfs/speed-scratch/USER/eplusout.expidf not found
   ...Summary of Errors that led to program termination:
   ..... Reference severe error count=0
   ..... Last severe error=
   ************* Warning:  Node connection errors not checked - most system input has not been read (see previous warning).
   ************* Fatal error -- final processing.  Program exited before simulations began.  See previous error messages.
   ************* EnergyPlus Warmup Error Summary. During Warmup: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Sizing Error Summary. During Sizing: 0 Warning; 0 Severe Errors.

**Comment by santoshphilip** [comment] 2020-10-24 00:30
Is there a chance you can run the file using EPLaunch on that computer

**Comment by santoshphilip** [comment] 2020-10-24 00:32
couple of other questions
- Can you share the code snippet that does the run
- What version of eppy is this

**Comment by intelligent-222** [comment] 2020-10-24 01:32
> Is there a chance you can run the file using EPLaunch on that computer

Dear Santosh, Thanks for your reply. I am very new to linux and I am not sure if I can run the EP through terminal. I can give it a try when I figure out how to run EP launch

**Comment by intelligent-222** [comment] 2020-10-24 01:35
> couple of other questions
> 
> * Can you share the code snippet that does the run
> * What version of eppy is this
![103](https://user-images.githubusercontent.com/70038498/97064912-b82a3f00-1577-11eb-89c6-586ce80412df.png)

**Comment by intelligent-222** [comment] 2020-10-24 01:36
> couple of other questions
> 
> * Can you share the code snippet that does the run
> * What version of eppy is this

![105](https://user-images.githubusercontent.com/70038498/97064925-c9734b80-1577-11eb-8b19-fb38ba8e052c.jpg)

**Comment by intelligent-222** [comment] 2020-10-24 01:36
> couple of other questions
> 
> * Can you share the code snippet that does the run
> * What version of eppy is this

![102](https://user-images.githubusercontent.com/70038498/97064931-db54ee80-1577-11eb-86d2-ea7428c6b6af.png)

**Comment by santoshphilip** [comment] 2020-10-24 02:17
> > Is there a chance you can run the file using EPLaunch on that computer
> 
> Dear Santosh, Thanks for your reply. I am very new to linux and I am not sure if I can run the EP through terminal. I can give it a try when I figure out how to run EP launch

My mistake. You cannot run EPLaunch on Linux.

**Comment by santoshphilip** [comment] 2020-10-24 02:20
can you try

     idf.run(expandobjects =True)

I will be checking messages for the next couple of hours.

**Comment by intelligent-222** [comment] 2020-10-24 03:29
Still same error. Let me explain and provide you with the file location and their contents to make sure I did everything right:

EP folder
[speed-submit] [/speed-scratch/USER] > ls
EP-8-9  EP-Input      eplusout.err  hello.py       template.sh  test.py
EP-9-2  eplusout.end  EP_versions   PythonEPPy.sh  test2.py

EP-8-9 folder:
[speed-submit] [/speed-scratch/USER/EP-8-9] > ls
Basement                                     EP-Compare              runepmacro
BasementGHT.idd                              EPMacro                 runreadvars
convertESOMTR                                ExpandObjects           Slab
Energy+.idd                                  HVAC-Diagram            SlabGHT.idd
energyplus                                   IDFVersionUpdater       Transition-V8-2-0-to-V8-3-0
EnergyPlus                                   ParametricPreprocessor  V8-2-0-Energy+.idd
EnergyPlus-8-9-0                             parser                  V8-3-0-Energy+.idd
EnergyPlus-8.9.0-40101eaafd-Linux-x86_64.sh  ReadVarsESO
Energy+.schema.epJSON                        runenergyplus

EP-Input folder:
[speed-submit] [/speed-scratch/USER/EP-Input] > ls
CAN_PQ_Montreal.Intl.AP.716270_CWEC.epw  simpleboxforHPC.idf  sTestFor8.9.idf

and here is the last changes that I have made to my code:


![code](https://user-images.githubusercontent.com/70038498/97067030-933dc800-1587-11eb-8c50-3d6ee930decf.JPG)

**Comment by santoshphilip** [comment] 2020-10-24 04:03
I am not seeing where the problem is coming from.
This may have to wait until tomorrow.

**Comment by intelligent-222** [comment] 2020-10-24 04:15
Sure. Good night

**Comment by santoshphilip** [comment] 2020-10-24 15:38
I did the following on linux with energyplus8.9 and it worked.
Can you try it out

make a virtual env.

    python3 -m venv ~/venvs/eppy_pypi
    source ~/venvs/eppy_pypi/bin/activate
    
    pip install -U pip
    pip install eppy 

Make a working directory

    mkdir test_expidf
    cd test_expidf

run this script:

    from eppy.modeleditor import IDF

    iddfile = "/usr/local/EnergyPlus-8-9-0/Energy+.idd"
    epwfile = "/usr/local/EnergyPlus-8-9-0/WeatherData/USA_CA_San.Francisco.Intl.AP.724940_TMY3.epw"
    fname = "/usr/local/EnergyPlus-8-9-0/ExampleFiles/HVACTemplate-5ZoneConstantVolumeChillerBoiler.idf"
    IDF.setiddname(iddfile)
    idf = IDF(fname, epwfile)
    idf.run()


All your output files will be in test_expidf

**Comment by htmehdi** [comment] 2020-10-24 17:37
Hi Santoshphilip,

Thank you for your reply. I tried to build the virtual environment and it gives me a stupid error. as I mentioned I am new to the Linux environment. Also, the HPC that I am working on is a little bit complicated and it has multiple layers. I will work on it today and will get beck to you soon. Unfortunately, I have limited access regarding installing and sometimes need admin access. I will work on the second part of your response to see if I can run an example using my python script.

here is the error:
source ~/venvs/eppy_pypi/bin/activate
Badly placed ()'s.

**Comment by htmehdi** [comment] 2020-10-24 17:53
I did all the following and same error:

pip install -U pip
pip install eppy 

mkdir test_expidf
cd test_expidf

>>> from eppy.modeleditor import IDF
>>> iddfile="/speed-scratch/USER/EP-8-9/EnergyPlus-8-9-0/Energy+.idd"
>>> epwfile="/speed-scratch/USER/EP-8-9/EnergyPlus-8-9-0/WeatherData/USA_CA_San.Francisco.Intl.AP.724940_TMY3.epw"
>>> fname="/speed-scratch/USER/EP-8-9/EnergyPlus-8-9-0/ExampleFiles/HVACTemplate-5ZoneConstantVolumeChillerBoiler.idf"
>>> IDF.setiddname(iddfile)
>>> idf=IDF(fname,epwfile)
>>> idf.run()


**  Fatal  ** Input file path /nfs/speed-scratch/USER/test_expidf/eplusout.expidf not found

these two files are created in test_expidf

eplusout.end  eplusout.err

**Comment by intelligent-222** [comment] 2020-10-24 19:20
Hi Santoshphilip,

Thank you for your reply. I tried to build the virtual environment and it gives me a stupid error. as I mentioned I am new to the Linux environment. Also, the HPC that I am working on is a little bit complicated and it has multiple layers. I will work on it today and will get beck to you soon. Unfortunately, I have limited access regarding installing and sometimes need admin access. I will work on the second part of your response to see if I can run an example using my python script.

here is the error:
source ~/venvs/eppy_pypi/bin/activate
Badly placed ()'s.

**Comment by intelligent-222** [comment] 2020-10-24 19:22
I did all the following and same error:

pip install -U pip
pip install eppy

mkdir test_expidf
cd test_expidf

from eppy.modeleditor import IDF
iddfile="/speed-scratch/USER/EP-8-9/EnergyPlus-8-9-0/Energy+.idd"
epwfile="/speed-scratch/USER/EP-8-9/EnergyPlus-8-9-0/WeatherData/USA_CA_San.Francisco.Intl.AP.724940_TMY3.epw"
fname="/speed-scratch/USER/EP-8-9/EnergyPlus-8-9-0/ExampleFiles/HVACTemplate-5ZoneConstantVolumeChillerBoiler.idf"
IDF.setiddname(iddfile)
idf=IDF(fname,epwfile)
idf.run()

** Fatal ** Input file path /nfs/speed-scratch/USER/test_expidf/eplusout.expidf not found

these two files are created in test_expidf

eplusout.end eplusout.err

**Comment by santoshphilip** [comment] 2020-10-24 20:00
looks like your EnergyPlus is not installed in the standard location. Can you check:

    ls /usr/local/EnergyPlus*

Tell me what you get

**Comment by santoshphilip** [comment] 2020-10-24 20:53
I take back my previous comment.
on Linux, idf.run() should work even if EnergyPlus is in an non-standard location

**Comment by santoshphilip** [comment] 2020-10-25 04:21
even if you are not an admin, you can install a virtualenv by doing

    python3 -m pip install --user virtualenv

and then do

    python3 -m venv ~/venvs/eppy_pypi
    source ~/venvs/eppy_pypi/bin/activate

    pip install eppy 

try it and see if it works.

**Comment by santoshphilip** [comment] 2020-10-25 16:32
You may want to install [VirtualBox](https://www.virtualbox.org) on your Windows machine.
Install [Linux](https://ubuntu.com/download/desktop) on VirtualBox.
Make your local linux install the same as that on your remote machine

it would be easier to figure out linux issues on a local machine rather than mess with the remote machine

In any case you are going to have a learning curve on it

**Comment by intelligent-222** [comment] 2020-10-26 18:25
Dear Santosh,

After deep review of the process, the HPC team has suggested me to run code twice and perform the following process. Based on your expertise, how can I fix the issue and skip the moving and renaming process that embedded into the HPC team suggestion. Here is what they have told me to run the following code:

rom eppy.modeleditor import IDF
iddfile="/speed-scratch/USER/EP-8-9/EnergyPlus-8-9-0/Energy+.idd"
epwfile="/speed-scratch/USER/EP-8-9/EnergyPlus-8-9-0/WeatherData/USA_CA_San.Francisco.Intl.AP.724940_TMY3.epw"
fname="/speed-scratch/USER/EP-8-9/EnergyPlus-8-9-0/ExampleFiles/HVACTemplate-5ZoneConstantVolumeChillerBoiler.idf"
IDF.setiddname(iddfile)
idf=IDF(fname,epwfile)
idf.run()


I have to run it twice as follow:

The first time it will fail. When it fails exit out of python, run

   ls -lsrt /tmp

to find the newest tmpXXXXXXXXX directory it created.
The run

   mv /tmp/tmpXXXXXXXX/expanded.idf ./eplusout.expidf

and run the above python script again. This time it will have 
eplusout.expidf in the directory.

**Comment by intelligent-222** [comment] 2020-10-26 19:21
Dear Santosh,

after deep review of the process, the HPC team has suggested me to run code twice and perform the following process. Based on your expertise, how can I fix the issue and skip the moving and renaming process that embedded into the HPC team suggestion. here is what they have told me to run the following code:

rom eppy.modeleditor import IDF
iddfile="/speed-scratch/USER/EP-8-9/EnergyPlus-8-9-0/Energy+.idd"
epwfile="/speed-scratch/USER/EP-8-9/EnergyPlus-8-9-0/WeatherData/USA_CA_San.Francisco.Intl.AP.724940_TMY3.epw"
fname="/speed-scratch/USER/EP-8-9/EnergyPlus-8-9-0/ExampleFiles/HVACTemplate-5ZoneConstantVolumeChillerBoiler.idf"
IDF.setiddname(iddfile)
idf=IDF(fname,epwfile)
idf.run()


I have to run it twice as follow:

The first time it will fail. When it fails exit out of python, run

   ls -lsrt /tmp

to find the newest tmpXXXXXXXXX directory it created.
The run

   mv /tmp/tmpXXXXXXXX/expanded.idf ./eplusout.expidf

and run the above python script again. This time it will have 
eplusout.expidf in the directory.

**Comment by intelligent-222** [comment] 2020-10-26 19:26
Finally we found a better solution. I should create a tmp folder and define it for python as follow. I test this and it works. still dont know exactly what was the reason of the issue but it works. I would like to share it with you to have your valuable comment:

As long as the file system that eppy uses for tmp is the same as what "speed-scratch" uses then there is no problem. I just have to tell it which tmp directory to use.

Make a tmp directory in /scratch-speed

  mkdir /scratch-speed/USER/tmp

I only have to make it once, maybe once in a while  delete old directories.

Then just tell python which tmp to use

  setenv TMPDIR /scratch-speed/USER/tmp

before running python.

**Comment by intelligent-222** [comment] 2020-10-26 19:35
> Finally we found a better solution. I should create a tmp folder and define it for python as follow. I test this and it works. still dont know exactly what was the reason of the issue but it works. I would like to share it with you to have your valuable comment:
> 
> As long as the file system that eppy uses for tmp is the same as what "speed-scratch" uses then there is no problem. I just have to tell it which tmp directory to use.
> 
> Make a tmp directory in /scratch-speed
> 
> mkdir /scratch-speed/USER/tmp
> 
> I only have to make it once, maybe once in a while delete old directories.
> 
> Then just tell python which tmp to use
> 
> setenv TMPDIR /scratch-speed/USER/tmp
> 
> before running python.

Here is the temporary solution the we have found before the one tha tI have mentioned above:

after deep review of the process, the HPC team has suggested me to run code twice and perform the following process. Based on your expertise, how can I fix the issue and skip the moving and renaming process that embedded into the HPC team suggestion. here is what they have told me to run the following code:

rom eppy.modeleditor import IDF
iddfile="/speed-scratch/USER/EP-8-9/EnergyPlus-8-9-0/Energy+.idd"
epwfile="/speed-scratch/USER/EP-8-9/EnergyPlus-8-9-0/WeatherData/USA_CA_San.Francisco.Intl.AP.724940_TMY3.epw"
fname="/speed-scratch/USER/EP-8-9/EnergyPlus-8-9-0/ExampleFiles/HVACTemplate-5ZoneConstantVolumeChillerBoiler.idf"
IDF.setiddname(iddfile)
idf=IDF(fname,epwfile)
idf.run()


I have to run it twice as follow:

The first time it will fail. When it fails exit out of python, run

   ls -lsrt /tmp

to find the newest tmpXXXXXXXXX directory it created.
The run

   mv /tmp/tmpXXXXXXXX/expanded.idf ./eplusout.expidf

and run the above python script again. This time it will have 
eplusout.expidf in the directory.

**Comment by santoshphilip** [comment] 2020-10-26 22:22
there may be a way of doing it without two runs.
I'll post on it soon.

### on posting code or errors :
to report your error/code in a fixed width format
put a blank line at the start
leave 4 spaces before each line of the error message
it will make it easier to read
error/code will show up as

error/code

    from eppy.modeleditor import IDF
    iddfile="/speed-scratch/USER/EP-8-9/EnergyPlus-8-9-0/Energy+.idd"
    epwfile="/speed-scratch/USER/EP-8-9/EnergyPlus-8-9-0/WeatherData/USA_CA_San.Francisco.Intl.AP.724940_TMY3.epw"
    fname="/speed-scratch/USER/EP-8-9/EnergyPlus-8-9-0/ExampleFiles/HVACTemplate-5ZoneConstantVolumeChillerBoiler.idf"
    IDF.setiddname(iddfile)
    idf=IDF(fname,epwfile)
    idf.run()

**Comment by santoshphilip** [comment] 2020-10-27 22:05
Can you try running the script below. 
Change pathnames for your circumstances.
I think it might work with 1 run.
Let me know what happens

    """single run EPLaunch style"""


    import os 
    from eppy.modeleditor import IDF
    from eppy.runner.run_functions import runIDFs

    def make_eplaunch_options(idf):
        """Make options for run, so that it runs like EPLaunch on Windows"""
        idfversion = idf.idfobjects['version'][0].Version_Identifier.split('.')
        idfversion.extend([0] * (3 - len(idfversion)))
        idfversionstr = '-'.join([str(item) for item in idfversion])
        fname = idf.idfname
        options = {
            # 'ep_version':idfversionstr, # runIDFs needs the version number
                # idf.run does not need the above arg
                # you can leave it there and it will be fine :-)
            'output_prefix':os.path.basename(fname).split('.')[0],
            'output_suffix':'C',
            'output_directory':os.path.dirname(fname),
            'readvars':True,
            'expandobjects':True
            }
        return options


    def main():
        iddfile = "/Applications/EnergyPlus-9-3-0/Energy+.idd" # change this for your operating system and E+ version
        IDF.setiddname(iddfile)
        epwfile = "USA_CA_San.Francisco.Intl.AP.724940_TMY3.epw"



        # File is from the Examples Folder
        idfname = "HVACTemplate-5ZoneBaseboardHeat.idf"
        idf = IDF(idfname, epwfile)
        theoptions = make_eplaunch_options(idf)
        idf.run(**theoptions)


    if __name__ == '__main__':
        main()

**Comment by santoshphilip** [comment] 2020-11-09 16:14
I am glad it worked out.
I'll go ahead and close the issue

**Closed by santoshphilip** 2020-11-09 16:14 UTC
