### ISSUE TITLE
[Bug] Working directory is changed when runnning an invalid idf

### ISSUE THREAD

**Issue by Wbec** [santoshphilip/eppy#208] opened 2018-10-02 00:08 UTC
If I run an idf with any invalid values, the `.run()` command has the side effect of changing the current working directory:
```python
from eppy.modeleditor import IDF
import os

# use any valid idf
IDF.setiddname('example_idd.idd')
idf = IDF('example_idf.idf', 'example_epw.epw')

# make the idf throw an error when run
idf.idfobjects['MATERIAL'][0].Thickness = 'Invalid Value'

print(os.getcwd())
idf.run()
print(os.getcwd())
```
The calls to `os.getcwd()` will display `/home/civil/Documents/Eppy/` and `/tmp/tmphqz6xpk1` respectively.  
This appears to be due to the end of the run function in eppy/eppy/runner/run_functions.py changing the current working directory, and then not always changing it back.

```python  
try:
    if verbose == 'v':
        check_call(cmd)
    elif verbose == 'q':
        check_call(cmd, stdout=open(os.devnull, 'w'))
    os.chdir(cwd) # This line will not be run if the previous line threw an error. <-----
       # It is responsible for changing back the working directory.
except CalledProcessError:
    # potentially catch contents of std out and put it in the error
    raise
return 'OK'
```
This could probably be fixed by trying something like:  
```python 
try:
    if verbose == 'v':
        check_call(cmd)
    elif verbose == 'q':
        check_call(cmd, stdout=open(os.devnull, 'w'))
except CalledProcessError:
    # potentially catch contents of std out and put it in the error
    raise
finally:
    os.chdir(cwd)
return 'OK'
```
I would make a pull request, but I am having a few issues with getting pytest to work on my machine.

**Comment by jamiebull1** [comment] 2018-10-02 06:29
Thanks for the report. I'll get it fixed. By the way, a pull request would be tested on the CI platform, so no need to run the tests locally, but since this ought to be a quick fix I'll make the change myself today.

**Comment by santoshphilip** [comment] 2018-10-03 18:52
@jamiebull1 , 
I merged your changes into the `develop` branch
cleanup after running the tests not removing some of the files generated in the tests. See below:

    (eppy)Santoshs-MacBook-Pro:eppy santosh$ git status
    On branch develop
    Your branch is up-to-date with 'origin/develop'.

    Untracked files:
      (use "git add <file>..." to include in what will be committed)

    	eppy/tests/eplusout.end
    	eppy/tests/eplusout.err
    	eppy/tests/in.idf

this happened after the changes you made. 
`master` branch is cleaning up fine.
Can you look into this.

**Comment by jamiebull1** [comment] 2018-10-03 23:19
Yep, I'll look tomorrow. I think I know where the problem is.

**Closed** 2018-10-04 06:06 UTC
Labels: bug
