### ISSUE TITLE
Installing eppy with python 3.6 / 3.7

### ISSUE THREAD

**Issue by mattia2** [santoshphilip/eppy#247] opened 2019-07-06 18:16 UTC
Dear All, 

apologies for the silly question but I cannot install eppy with python 3.6.4. Here you can find the error:
![pic](https://user-images.githubusercontent.com/52608217/60759785-74c65d00-a022-11e9-85b3-d970c2752da9.JPG)

How can I overcome this?

Many thanks for your support,

Mattia

**Comment by santoshphilip** [comment] 2019-07-06 22:35
Looks like a bug. 
I'll look into it

**Comment by santoshphilip** [comment] 2019-07-06 22:42
That was a bug
It has been fixed in branch `i247_install`

For the moment, you can install using::

    pip install https://github.com/santoshphilip/eppy/archive/i247_install.zip

Let me know if it works

**Comment by jamiebull1** [comment] 2019-07-07 08:57
What was the issue here, @santoshphilip? Is it something we can add a test for so we don't get a regression?

**Comment by mattia2** [comment] 2019-07-08 08:20
Thank you very much. I was able to install eppy with py 3.6. 
Any chance to install eppy with Anaconda? I tried with the same script (python 3.7.3 with Anaconda)

![Capture](https://user-images.githubusercontent.com/52608217/60794352-819d9a80-a161-11e9-8d08-9dc6bc8d624d.JPG)

Many thanks in advance,

Mattia

**Comment by santoshphilip** [comment] 2019-07-08 18:10
@mattia2 , Anaconda may need a new version (with the bug fix) on https://pypi.org
I'll try and get a new release done in a few days.

**Comment by santoshphilip** [comment] 2019-07-08 18:13
@jamiebull1 ,  
The bug was in setup.py
I am not sure how to test the install process automatically. 

I am chasing some deadlines right now. I'll post my notes on this when I get a moment :-)

**Comment by jamiebull1** [comment] 2019-07-08 20:36
That's strange. The CI uses setup.py, so should have caught it. Yes, let me
know when you get a chance and I'll see if there's any improvement we can
make.

**Comment by santoshphilip** [comment] 2019-07-14 15:55
made a new release in pypi.org
Now `pip install eppy` or `pip install -U eppy` will work

**Comment by MaheshJayachander** [comment] 2019-07-17 14:10
hi @santoshphilip , facing the same issue with conda install eppy, any updates on this matter would be helpfull.

**Comment by santoshphilip** [comment] 2019-07-17 17:48
@MaheshJayachander , 
I thought the new version I released would work with conda
Looks like it is not.

I don't have conda installed. So I can't test it here:
I assume you would do:

    conda install eppy
    # or
    conda install https://github.com/santoshphilip/eppy/archive/master.zip

Can you post the error message.

**Comment by MaheshJayachander** [comment] 2019-07-18 03:16
![conda install failure](https://user-images.githubusercontent.com/49056624/61426581-75bb9080-a938-11e9-8a7f-00cda746567b.PNG)

this is the error I am facing @santoshphilip

**Comment by jamiebull1** [comment] 2019-07-18 10:30
Do we produce wheels for conda? As far as I'm aware it's not part of the build process. We could look at tagging it onto the CI process, but I don't think there are any difficult dependency issues that make it necessary. 

When I install eppy in a conda env, I just activate the env, then `pip install eppy` as usual.

**Comment by MaheshJayachander** [comment] 2019-07-18 11:14
got it @jamiebull1 , did `pip install eppy` in anaconda prompt, got it installed. 
Thank you.

**Comment by mattia2** [comment] 2019-07-21 09:18
Thanks @jamiebull1 @santoshphilip - it works :)

**Comment by santoshphilip** [comment] 2019-07-22 00:33
I am closing this issue as **resolved**
@jamiebull1 , I'll open a new issue to work on why the tests did not catch this failure

**Closed by santoshphilip** 2019-07-22 00:33 UTC
Labels: bug
