### ISSUE TITLE
 An error with “runIDFs”

### ISSUE THREAD

**Issue by hxy1027** [santoshphilip/eppy#381] opened 2022-04-17 13:20 UTC
**Hello, I have a problem. My computer can't run “runIDFs”, and I'll simplify the input as follows:**
My original program was very long and could run in the laptop, but the laptop could not support a long time running, so I changed to the desktop, but the desktop kept reporting errors. I simplified it to the simplest form, and I hope you can help to check whether there is any problem

```
from eppy.modeleditor import IDF
from eppy.runner.run_functions import runIDFs
import os
def make_eplaunch_options(idf):
    idfversion = idf.idfobjects['version'][0].Version_Identifier.split('.')
    idfversion.extend([0] * (3 - len(idfversion)))
    idfversionstr = '-'.join([str(item) for item in idfversion])
    fname = idf.idfname
    options = {
        'ep_version': idfversionstr,  # runIDFs needs the version number
        'output_prefix': os.path.basename(fname).split('.')[0],
        'output_suffix': 'C',
        # 'output_directory': os.path.dirname(fname),
        'output_directory': r'D:\hxy_py0\3shiyingdu\code\csvout',
        'readvars': True,
        'expandobjects': True
    }
    return options
def main():
    iddfile = "D:/EnergyPlusV9-2-0/Energy+.idd"
    IDF.setiddname(iddfile)
    epwfile = r"D:\hxy_py0\3shiyingdu\code\weather\tianjin\tianjin1981.epw"
    idfname1 = r"D:\hxy_py0\3shiyingdu\code\idfout\0idfroom1981.idf"
    idfname2 = r"D:\hxy_py0\3shiyingdu\code\idfout\0idfroom1982.idf"
    fnames = [idfname1, idfname2]
    idfs = (IDF(fname, epwfile) for fname in fnames)
    runs = ((idf, make_eplaunch_options(idf) ) for idf in idfs)
    num_CPUs = 2
    runIDFs(runs, num_CPUs)
if __name__ == '__main__':
    main()
```

**The result is an error:**

```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\EABteam\AppData\Local\Continuum\anaconda3\envs\python37hxy\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\EABteam\AppData\Local\Continuum\anaconda3\envs\python37hxy\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "C:\Users\EABteam\AppData\Local\Continuum\anaconda3\envs\python37hxy\lib\site-packages\eppy\runner\run_functions.py", line 197, in multirunner
    run(*args[0], **args[1])
  File "C:\Users\EABteam\AppData\Local\Continuum\anaconda3\envs\python37hxy\lib\site-packages\eppy\runner\run_functions.py", line 326, in run
    check_call(cmd)
  File "C:\Users\EABteam\AppData\Local\Continuum\anaconda3\envs\python37hxy\lib\subprocess.py", line 358, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Users\EABteam\AppData\Local\Continuum\anaconda3\envs\python37hxy\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\EABteam\AppData\Local\Continuum\anaconda3\envs\python37hxy\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\EABteam\AppData\Local\Continuum\anaconda3\envs\python37hxy\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2]  The system cannot find the file specified
"""
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "D:/hxy_py0/3shiyingdu/code/ceshinew.py", line 55, in <module>
    main()
  File "D:/hxy_py0/3shiyingdu/code/ceshinew.py", line 45, in main
    runIDFs(runs, -1)
  File "C:\Users\EABteam\AppData\Local\Continuum\anaconda3\envs\python37hxy\lib\site-packages\eppy\runner\run_functions.py", line 163, in runIDFs
    pool.map(multirunner, prepared_runs)
  File "C:\Users\EABteam\AppData\Local\Continuum\anaconda3\envs\python37hxy\lib\multiprocessing\pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Users\EABteam\AppData\Local\Continuum\anaconda3\envs\python37hxy\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
FileNotFoundError: [WinError 2]  The system cannot find the file specified
```
**I have looked at other people's problems and checked the similar problems reported as errors, but it was useless. Well, the CMD has run successfully and is ready to run(Refer to this question:https://github.com/santoshphilip/eppy/issues/319), thank you**

**Comment by hxy1027** [comment] 2022-04-17 13:22
Besides, It is possible to run a separate EnergyPlus directly, but an error will be reported if it is used in parallel

**Comment by santoshphilip** [comment] 2022-04-18 04:44
I am not immediately seeing what the problem is. I need to work on it bit figure it out.

**Comment by santoshphilip** [comment] 2022-04-19 07:01
We may have to try different things out. Try this first

change 

     'output_directory': r'D:\hxy_py0\3shiyingdu\code\csvout'
     
to

     'output_directory': "D:/hxy_py0/3shiyingdu/code/csvout"

change

    epwfile = r"D:\hxy_py0\3shiyingdu\code\weather\tianjin\tianjin1981.epw"
    idfname1 = r"D:\hxy_py0\3shiyingdu\code\idfout\0idfroom1981.idf"
    idfname2 = r"D:\hxy_py0\3shiyingdu\code\idfout\0idfroom1982.idf"

to

    epwfile = "D:/hxy_py0/3shiyingdu/code/weather/tianjin/tianjin1981.epw"
    idfname1 = "D:/hxy_py0/3shiyingdu/code/idfout/0idfroom1981.idf"
    idfname2 = "D:/hxy_py0/3shiyingdu/code/idfout/0idfroom1982.idf"
    

Send me the error messages you get

**Comment by hxy1027** [comment] 2022-04-19 09:04
Thank you for your reply, I have modified the expression of the file path according to your suggestion
But still the same error, I copied the entire output profile here
```
D:\anaconda\envs\python37xy\python.exe D:/hxy_py0/3shiyingdu/code/ceshinew.py

C:/EnergyPlusV9-2-0\energyplus.exe --weather D:\hxy_py0\3shiyingdu\code\weather\tianjin\tianjin1981.epw --output-directory D:\hxy_py0\3shiyingdu\code\csvout --expandobjects --readvars --output-prefix 0idfroom1981 --output-suffix C D:\hxy_py0\3shiyingdu\code\multi_runs\idf_0\in.idf


C:/EnergyPlusV9-2-0\energyplus.exe --weather D:\hxy_py0\3shiyingdu\code\weather\tianjin\tianjin1981.epw --output-directory D:\hxy_py0\3shiyingdu\code\csvout --expandobjects --readvars --output-prefix 0idfroom1982 --output-suffix C D:\hxy_py0\3shiyingdu\code\multi_runs\idf_1\in.idf

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "D:\anaconda\envs\python37xy\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "D:\anaconda\envs\python37xy\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "D:\anaconda\envs\python37xy\lib\site-packages\eppy\runner\run_functions.py", line 197, in multirunner
    run(*args[0], **args[1])
  File "D:\anaconda\envs\python37xy\lib\site-packages\eppy\runner\run_functions.py", line 326, in run
    check_call(cmd)
  File "D:\anaconda\envs\python37xy\lib\subprocess.py", line 358, in check_call
    retcode = call(*popenargs, **kwargs)
  File "D:\anaconda\envs\python37xy\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "D:\anaconda\envs\python37xy\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "D:\anaconda\envs\python37xy\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:/hxy_py0/3shiyingdu/code/ceshinew.py", line 31, in <module>
    main()
  File "D:/hxy_py0/3shiyingdu/code/ceshinew.py", line 29, in main
    runIDFs(runs, num_CPUs)
  File "D:\anaconda\envs\python37xy\lib\site-packages\eppy\runner\run_functions.py", line 163, in runIDFs
    pool.map(multirunner, prepared_runs)
  File "D:\anaconda\envs\python37xy\lib\multiprocessing\pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "D:\anaconda\envs\python37xy\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
FileNotFoundError: [WinError 2] The system cannot find the file specified

Process finished with exit code 1

```

**Comment by hxy1027** [comment] 2022-04-19 09:06
> Thank you for your reply, I have modified the expression of the file path according to your suggestion But still the same error, I copied the entire output profile here
> 
> ```
> D:\anaconda\envs\python37xy\python.exe D:/hxy_py0/3shiyingdu/code/ceshinew.py
> 
> C:/EnergyPlusV9-2-0\energyplus.exe --weather D:\hxy_py0\3shiyingdu\code\weather\tianjin\tianjin1981.epw --output-directory D:\hxy_py0\3shiyingdu\code\csvout --expandobjects --readvars --output-prefix 0idfroom1981 --output-suffix C D:\hxy_py0\3shiyingdu\code\multi_runs\idf_0\in.idf
> 
> 
> C:/EnergyPlusV9-2-0\energyplus.exe --weather D:\hxy_py0\3shiyingdu\code\weather\tianjin\tianjin1981.epw --output-directory D:\hxy_py0\3shiyingdu\code\csvout --expandobjects --readvars --output-prefix 0idfroom1982 --output-suffix C D:\hxy_py0\3shiyingdu\code\multi_runs\idf_1\in.idf
> 
> multiprocessing.pool.RemoteTraceback: 
> """
> Traceback (most recent call last):
>   File "D:\anaconda\envs\python37xy\lib\multiprocessing\pool.py", line 121, in worker
>     result = (True, func(*args, **kwds))
>   File "D:\anaconda\envs\python37xy\lib\multiprocessing\pool.py", line 44, in mapstar
>     return list(map(*args))
>   File "D:\anaconda\envs\python37xy\lib\site-packages\eppy\runner\run_functions.py", line 197, in multirunner
>     run(*args[0], **args[1])
>   File "D:\anaconda\envs\python37xy\lib\site-packages\eppy\runner\run_functions.py", line 326, in run
>     check_call(cmd)
>   File "D:\anaconda\envs\python37xy\lib\subprocess.py", line 358, in check_call
>     retcode = call(*popenargs, **kwargs)
>   File "D:\anaconda\envs\python37xy\lib\subprocess.py", line 339, in call
>     with Popen(*popenargs, **kwargs) as p:
>   File "D:\anaconda\envs\python37xy\lib\subprocess.py", line 800, in __init__
>     restore_signals, start_new_session)
>   File "D:\anaconda\envs\python37xy\lib\subprocess.py", line 1207, in _execute_child
>     startupinfo)
> FileNotFoundError: [WinError 2] The system cannot find the file specified
> """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "D:/hxy_py0/3shiyingdu/code/ceshinew.py", line 31, in <module>
>     main()
>   File "D:/hxy_py0/3shiyingdu/code/ceshinew.py", line 29, in main
>     runIDFs(runs, num_CPUs)
>   File "D:\anaconda\envs\python37xy\lib\site-packages\eppy\runner\run_functions.py", line 163, in runIDFs
>     pool.map(multirunner, prepared_runs)
>   File "D:\anaconda\envs\python37xy\lib\multiprocessing\pool.py", line 268, in map
>     return self._map_async(func, iterable, mapstar, chunksize).get()
>   File "D:\anaconda\envs\python37xy\lib\multiprocessing\pool.py", line 657, in get
>     raise self._value
> FileNotFoundError: [WinError 2] The system cannot find the file specified
> 
> Process finished with exit code 1
> ```

**Comment by santoshphilip** [comment] 2022-04-19 13:36
copy this line to the terminal and run it

    C:/EnergyPlusV9-2-0\energyplus.exe --weather D:\hxy_py0\3shiyingdu\code\weather\tianjin\tianjin1981.epw --output-directory D:\hxy_py0\3shiyingdu\code\csvout --expandobjects --readvars --output-prefix 0idfroom1981 --output-suffix C D:\hxy_py0\3shiyingdu\code\multi_runs\idf_0\in.idf

send me the error message, if any
FYI: this is the second line from your error message

What version of eppy are you running?

**Comment by santoshphilip** [comment] 2022-04-19 15:41
quite likely that the error may be coming from th `C:/`  and  `D:/` mismatch 

I need to revisit the eppy code to find out how eppy is finding the EnergyPlus.exe
There is a chance that this is hardcoded. Which raises the question on how should eppy run E+ when E+ is installed in a non-standard location.

Can you install E+ in C:/
(Although I suspect you don't have admin access to the C drive)

What time zone are you in ? I am trying to get a sense of when I should post messages here.

**Comment by santoshphilip** [comment] 2022-04-19 15:42
OK ... I see in your message that you could not install E+ in C Drive.
I'll try to make a update for that will allow E+ to run if it is in a non-standard location.

**Comment by hxy1027** [comment] 2022-04-19 16:25
Great news! Instead of trying to re-download it, I just copied the Energyplus folder from the `D:/` drive to the `C:/`, re-ran it, and it ran correctly without errors!!!
（Even though this method doesn't solve the underlying problem, it can still solve an immediate problem if used in a hurry）

Once again, thank you very much!

**Comment by santoshphilip** [comment] 2022-04-19 17:10
That's a good hack.
Go ahead and close this issue.

I'll follow up on issue #382

**Closed** 2022-04-20 02:10 UTC
