### ISSUE TITLE
readhtml.py issue error to read result html file for EP v8.7

### ISSUE THREAD

**Issue by katsuya0719** [santoshphilip/eppy#152] opened 2017-04-15 02:45 UTC
Hi!
I have been using eppy to parse the result html file from EnergyPlus and it have been working without any problem.  
However, since updating to v8.7, readhtml.py start to issue following error.  
```
   File "main.py", line 33, in setfolder
    self.htables=readhtml.titletable(html)
  File "C:\Users\obakatsu\Anaconda3\lib\site-packages\eppy\results\readhtml.py", line 92, in titletable
    titlerows = [(tl.contents[0], t2m(tb)) for tl, tb in titletables]
  File "C:\Users\obakatsu\Anaconda3\lib\site-packages\eppy\results\readhtml.py", line 92, in <listcomp>
    titlerows = [(tl.contents[0], t2m(tb)) for tl, tb in titletables]
  File "C:\Users\obakatsu\Anaconda3\lib\site-packages\eppy\results\readhtml.py", line 55, in table2val_matrix
    raise NotSimpleTable("Not able read a cell in the table as a string")
eppy.results.readhtml.NotSimpleTable: Not able read a cell in the table as a string
```
If anyone has idea how html file structure changed and how I can fit to it, I appreciate your advice.   
Thank you!

**Comment by santoshphilip** [comment] 2017-04-15 15:07
I don't think the html reader is used much. 

So you may be the expert and best positioned to fix it :-)
Would you like to try ?

**Comment by katsuya0719** [comment] 2017-04-17 03:46
> I don't think the html reader is used much.

Could you explain me more detail? Do you mean that you guess error is not caused by readhtml.py? or generally, readhtml.py is not being used in eppy?



> So you may be the expert and best positioned to fix it :-)
> Would you like to try ?

Sure. Let me try to fix this when I have time.

**Comment by santoshphilip** [comment] 2017-04-19 18:26
I am sorry I was not clear. The error is caused by readhtml.py
Since you are using it, I hope you can have a go at fixing it.

I wrote readhtml.py thinking that I would use it a lot. I discovered that I don't use it much at all. I just assumed that others are not using it either. Of course I am wrong, since you are using it.

**Comment by santoshphilip** [comment] 2017-08-12 15:16
I have fix this issue in branch i152_readhtml.
It was a lot more difficult that I anticipated. 
The work is not complete, as the code still needs some cleanup.

I made two changes in the requirements.txt file

    pytest==3.0.2
    lxml>=3.8.0

some tests for eppy.modelmaker were failing with the latest pytest. So I had to use an older version of pytest. I'll open an new issue for this.

**Comment by santoshphilip** [comment] 2017-08-13 06:25
@katsuya0719 I have fixed the issue and cleaned up the code.

Can you test it with a couple of files to see if it works. (test branch `i152_readhtml _1`)
Once you test it, I'll merge it into the `develop` branch and it will get into the next release

**Comment by santoshphilip** [comment] 2017-08-13 07:35
- tests are passing on python2
- python3 tests are failing

**Comment by santoshphilip** [comment] 2017-08-14 01:30
This has been fixed and merged into develop

**Closed by santoshphilip** 2017-08-14 01:30 UTC
